version: '3.8'
services:
  # PostgreSQL Service
  postgres:
    image: postgres:14
    container_name: waterdb-postgres
    environment:
      POSTGRES_DB: waterdb
      POSTGRES_USER: wateruser
      POSTGRES_PASSWORD: waterpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - water-connection-network

  # Zookeeper Service
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - water-connection-network

  # Kafka Service
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - water-connection-network

volumes:
  postgres_data:

networks:
  water-connection-network:
    driver: bridge
